packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  msw: true

shellEmulator: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
patchedDependencies:
  flomise@0.0.6: patches/flomise@0.0.6.patch
