/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiliNovelNidRouteImport } from './routes/bili.novel.$nid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiliNovelNidRoute = BiliNovelNidRouteImport.update({
  id: '/bili/novel/$nid',
  path: '/bili/novel/$nid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bili/novel/$nid': typeof BiliNovelNidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bili/novel/$nid': typeof BiliNovelNidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bili/novel/$nid': typeof BiliNovelNidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bili/novel/$nid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bili/novel/$nid'
  id: '__root__' | '/' | '/bili/novel/$nid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiliNovelNidRoute: typeof BiliNovelNidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bili/novel/$nid': {
      id: '/bili/novel/$nid'
      path: '/bili/novel/$nid'
      fullPath: '/bili/novel/$nid'
      preLoaderRoute: typeof BiliNovelNidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiliNovelNidRoute: BiliNovelNidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
